### ISSUE TITLE
Trace file is almost empty

### ISSUE THREAD

**Issue by Wyverex42** [fredemmott/OpenXR-Tracing#14]
Hey, 

I've tried to use this today and the etl file is almost empty
![image](https://github.com/fredemmott/OpenXR-Tracing/assets/16905876/bdbefd5e-7637-4840-8269-88b0757cbbae)

I'm using the pre-built binaries, the tracing layer is the only installed layer atm
![image](https://github.com/fredemmott/OpenXR-Tracing/assets/16905876/c6808cdc-8bee-4362-8e31-9c22b8504b59)

Then I'm doing:
```
wpr -start OXRTracing.wprp -filemode
```
Then I start an OpenXR test app (doesn't really matter which one though, same result for BeatSaber e.g.) and after a while I do
```
wpr -stop Trace.etl
```

The content of the etl file is always the same. 

Am I missing something else?

**Comment by fredemmott** [comment]
Those steps look correct; this sounds like either a 32-bit vs 64-bit issue, or an issue loading the layer; can you share a screenshot of the layers list in openxr explorer?

**Comment by fredemmott** [comment]
<img width="109" alt="image" src="https://github.com/fredemmott/OpenXR-Tracing/assets/360927/12aee734-0b92-4b20-a5c1-e187f8a08fbe">


This should be pointing at the json file, not the dll; how did you add it to the registry? The install script adds the json

**Comment by Wyverex42** [comment]
Oh gosh, you're right. Completely missed that, thanks!
