### ISSUE TITLE
Install modes -First and -Last are not working correctly

### ISSUE THREAD

**Issue by Wyverex42** [fredemmott/OpenXR-Tracing#15]
No matter whether I use `-Mode First` or `-Mode Last`, the layer is always last in the list in my registry. Shouldn't the installer script recreate the entries depending on the selected order?

**Comment by fredemmott** [comment]
>  always last in the list in my registry.

How are you determining this?

If it's regedit, that always shows in alphabetical order; list-openxr-layers.ps1 from https://github.com/fredemmott/openxr-layer-scripts/releases/latest is a more useful tool , or openxr explorer

**Comment by Wyverex42** [comment]
> If it's regedit, that always shows in alphabetical order; 

That can't be true. You can e.g. copy a path that's higher up in the list, then delete that key and re-add it at the end. It will stay at the end, there's no sorting going on.

I've also had issues with layer ordering in the past, e.g. here: https://github.com/mbucchia/OpenXR-Toolkit/issues/484
The crash was my fault in the end but influencing the layer ordering in the registry definitely had an impact

**Comment by fredemmott** [comment]
the openxr layer order is usually 'in order it was added to the registry', though technically undefined behavior on windows.

regedit **does not** show it accurately, but yes, deleting and re-adding a value in regedit will move it to the end

Are you able to reproduce this when using openxr explorer or the list-openxr-layers script for this?

The list-openxr-layers script exists exactly for this reason.

**Comment by Wyverex42** [comment]
I can confirm that the script is working correctly when checking with your `list-openxr-layers.ps1` script. I wasn't aware that the layer order via the registry isn't well-defined. 

Thank you for writing this trace layer, btw, it's come in very handy today!
